version: '3.8'

services:
  # Banco de Dados MySQL
  mysql:
    image: mysql:8.0
    container_name: frete-inteligente-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: frete_inteligente
      MYSQL_USER: frete
      MYSQL_PASSWORD: frete
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    networks:
      - frete-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend Spring Boot
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frete-inteligente-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: h2
      # Para usar MySQL, descomente as linhas abaixo e comente a linha acima
      # SPRING_PROFILES_ACTIVE: mysql
      # SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/frete_inteligente?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      # SPRING_DATASOURCE_USERNAME: frete
      # SPRING_DATASOURCE_PASSWORD: frete
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - frete-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Frontend Next.js
  frontend:
    build:
      context: ./transport-app
      dockerfile: Dockerfile
    container_name: frete-inteligente-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
    depends_on:
      - backend
    networks:
      - frete-network

networks:
  frete-network:
    driver: bridge

volumes:
  db_data:

